### PR TITLE
[♻️ REFACTOR] Button component added  [🛠 FIX] Code has been formatted

### LINKED ISSUE #35: Button Primary and Secondary
Main Button with two diferent ways to be implemented, primary or secondary

### PR DESCRIPTION
**Pull request by juliodenis**

### CODE REVIEW

**Review by WS-Jedp — APPROVED** [review]
Beatiful code 👨‍🎨

**Review by andresmorenoj — CHANGES_REQUESTED** [review]
Add the className `container__test` to the div with the className `button__container` or put that div inside the div with the className `julio__components__test`. If there is any error or doesn't look well after doing that, you can leave it as it is right now.

**Comment by andresmorenoj** [comment]
@jfdenis Remember to linked this PR with one of the issues in the list of issues. 👍

**Review by andresmorenoj — APPROVED** [review]
Great!!! 👍👍

**Pull request merged**
