### PR TITLE
[➕ADD] ProfilePicture component added

### LINKED ISSUE #37: Profile Picture
There are some styles to show a profile picture, so it must be a component

### PR DESCRIPTION
**Pull request by juliodenis**
I was wondering if I should create a function that set the image width and height or if it will be set as the component as called
for instance:

`<ProfilePicture source={mySource} alt={myAlt} width={'30px'} height={'30px'} active/>`
The width and height prop will be received by a function and this one will set them.
Or 
`<ProfilePicture className='setTheStylesHere'/>`
When you call the component set the styles with a className

### CODE REVIEW

**Review by WS-Jedp — CHANGES_REQUESTED** [review]
@jfdenis Do the merge into the Develop branch :p 

And about the function question, for me is better create a class, maybe can be reuseful in the future :D

**Comment by juliodenis** [comment]
Oh, yes 😅😅😅

**Review by andresmorenoj — CHANGES_REQUESTED** [review]
I think the profile image should have a width and height by default as it will be the same size all over the application, so maybe a function for that is no necessary, the only thing we need to make sure is that the image can be full responsive.
@WS-Jedp What do you think?
@jfdenis Please update the PR to be merge into the develop branch as I see that it is requiring to be merge with master.

**Comment by WS-Jedp** [comment]
> I think the profile image should have a width and height by default as it will be the same size all over the application, so maybe a function for that is no necessary, the only thing we need to make sure is that the image can be full responsive.
> @WS-Jedp What do you think?
> @jfdenis Please update the PR to be merge into the develop branch as I see that it is requiring to be merge with master.

Exactly, a class with responsive styles should be enough to manage the sizes of the ProfilePicture

**Comment by juliodenis** [comment]
I have done a new pull request to develop branch. Can I close this one?

**Comment by WS-Jedp** [comment]
> I have done a new pull request to develop branch. Can I close this one?

Yep, no problem

**Pull request closed without merging**
